# Generated by Django 4.0.2 on 2022-02-13 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ad',
            old_name='created_time',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='ad',
            old_name='updated_time',
            new_name='updated_at',
        ),
        migrations.RenameField(
            model_name='image',
            old_name='created_time',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='image',
            old_name='updated_time',
            new_name='updated_at',
        ),
    ]
